"""Initial migration

Revision ID: eb5f115742dd
Revises: 
Create Date: 2026-09-01 14:33:30.969852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb5f115742dd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('people_gender_check'), 'people', type_='check')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(op.f('people_gender_check'), 'people', "gender::text = ANY (ARRAY['М'::character varying, 'Ж'::character varying]::text[])")
    # ### end Alembic commands ###
